### ISSUE TITLE
Mac Address Issue in IOS Build

### ISSUE THREAD

**Issue by LiftTrack** [dotnet-bluetooth-le/dotnet-bluetooth-le#644] opened 2022-11-28 13:43 UTC
Hi,

I am using Plugin.BLE, I am facing one issue, I am unable to get Mac Id of the discovered devices by advertisements. Amazing fact is i am able to get Mac address of discovered devices in Android. I am using same plugin for both. can you help me in this issue or suggest me how can i get Mac address of discovered devices in IOS xamarin forms. In Android version, it is available in "e.Device.NativeDevice" which I get from advertisements but in IOS plugin i am unable to get Mac address of discovered devices.

Please help me in it, if there is any solution for it.

**Comment by smsissuechecker** [comment] 2022-11-28 13:43
Hi @LiftTrack,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment] 2022-11-30 09:50
Duplicate of #645.

**Closed by janusw** 2022-11-30 09:50 UTC
Labels: question, os:iOS
