### ISSUE TITLE
Any plans on making this work for UWP?

### ISSUE THREAD

**Issue by dgerchcovich** [dotnet-bluetooth-le/dotnet-bluetooth-le#530] opened 2021-07-26 05:28 UTC
Awesome package.
But are there any plans on making this work for UWP?

Each time I try to connect to a device, or disconnect, or run device discovery, it fails.
Thanks,

**Comment by smsissuechecker** [comment] 2021-07-26 05:28
Hi @dgerchcovich,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by adabru** [comment] 2023-10-08 23:55
This is a duplicate of https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/14.
@dgerchcovich I think you can close this one. I didn't try but https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/issues/14 suggests that UWP should be working from version 2.2.0 onwards.

**Comment by janusw** [comment] 2023-10-09 06:27
> This is a duplicate of #14.

True.

> I didn't try but #14 suggests that UWP should be working from version 2.2.0 onwards.

There has never actually been a final 2.2.0 release, but UWP support has been available since the 2.2.0-pre releases, and it is part of the stable release 3.0.0 now.

However, it may well be that individual features do not work fully yet. If you find any issues with the UWP support in 3.0.0, please open a new issue. I'm closing this one.

**Closed by janusw** 2023-10-09 06:27 UTC
Labels: os:Windows
