### ISSUE TITLE
[WinUI] [3.1.0-beta.1] introduces null IDevice(s) to device lists

### ISSUE THREAD

**Issue by axa88** [dotnet-bluetooth-le/dotnet-bluetooth-le#828] opened 2024-03-20 08:27 UTC
Not observed in released v3.0x this beta introduces null IDevice to device collections.
This is most easily observed when scanning for devices and receiving null items in the IAdapter.DiscoveredDevices ReadOnlyList

Earlier testing indicated if devices are already Bonded/Connected the corresponding listing will also have null devices, I assume these share a common IDevice source

## Expected behavior
Null Devices not in listing as in earlier release

## Actual behavior
Null Devices in listing

![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/13371986/f650faae-0130-4ddc-9e6c-8e4a5bde62e1)

## Configuration

**Version of the Plugin:** e.g. 3.1 beta 1

**Platform:**
![image](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/assets/13371986/df514f94-8a8d-469e-b12e-bc21414313d8)

**Device:**

```
Device name	Portable
Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Device ID	2F7EBCF5-2024-4778-9E85-988D5FD862D6
System type	64-bit operating system, x64-based processor

Intel Dual Band Wireless-AC 8265, Wi-Fi 2x2 802.11ac + **Bluetooth 4.1**, M.2 card
```

**Comment by smsissuechecker** [comment] 2024-03-20 08:27
Hi @axa88,

I'm the friendly issue checker.
It seems like (25.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by janusw** [comment] 2024-05-08 08:38
Since this is a regression of 3.1.x wrt 3.0.x, I think it should be fixed before the final 3.1.0 release.

Looking through the git history between 3.0.0 and 3.1.0-beta.1, one commit that makes significant changes to `Adapter.AdvertisementReceived` is 4fca5e389052ecc988f85d3bb939f1bfd84ad72e. Could this be the culprit here, @AskBojesen?

**Comment by AskBojesen** [comment] 2024-05-08 11:44
Ok - I will look into this now

**Comment by axa88** [comment] 2024-05-09 14:51
> Nice finding @axa88 and nice spotted @janusw!

if you liked that, i think i'll soon have more...  😃

**Comment by AskBojesen** [comment] 2024-05-09 15:46
> > Nice finding @axa88 and nice spotted @janusw!
> 
> if you liked that, i think i'll soon have more... 😃

Great!, I have time these coming days for that. Let us stick to bugfixes - no new features

**Closed** 2024-05-11 07:37 UTC
Labels: os:Windows, regression

**Comment by axa88** [comment] 2024-05-11 17:15
> Great!, I have time these coming days for that. Let us stick to bugfixes - no new features

@AskBojesen 
[fwiw](https://github.com/dotnet-bluetooth-le/dotnet-bluetooth-le/pull/849#issuecomment-2105950407)

**Comment by janusw** [comment] 2024-05-13 14:38
> @janusw: Suggest to close this issue - since PR #848 is merged

It's closed already! 😬
